
notifications:
  email:
    on_success: never
    on_failure: change

sudo: required
dist: xenial

env:
  global:
    - TMPDIR=/tmp

install:
  - curl -L https://git.io/get_helm.sh | bash -s -- -v v2.16.1

services:
  - docker
  
script:
  - make
