dist: xenial
sudo: required

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - docker

env:
  global:
    - TMPDIR=/tmp

install:
  - curl -L https://git.io/get_helm.sh | bash -s -- -v v2.16.1
  - helm init --client-only

script:
  - make
