## Default values for Traefik
image:
  name: traefik
  tag: 2.0.0
#
deployment:
  replicas: 1
#
ports:
  http:
    port: 8000
  https:
    port: 8443
#
logs:
  loglevel: INFO
#
yaml:
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"
