## Default values for Traefik
image:
  name: traefik
  tag: 2.0.2
#
deployment:
  replicas: 1
#
ports:
  web:
    port: 8000
    # nodePort: 30000
  websecure:
    port: 8443
    # nodePort: 30001
  traefik:
    port: 9000
#
#service:
#  externalTrafficPolicy: Cluster
#  type: LoadBalancer

logs:
  loglevel: INFO
#
yaml:
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"
#  nodeSelector: {}
#  tolerations: []
