apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 27.0.0
# renovate: image=traefik
appVersion: v2.11.0
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: remove null annotations on dashboard `IngressRoute`"
    - "fix(rbac): do not create clusterrole for namespace deployment on Traefik v3"
    - "feat: restrict access to secrets"
    - "feat!: :boom: refactor custom services and port exposure"
    - "chore(release): 🚀 publish v27.0.0"
