apiVersion: v2
name: customer-support-panel-frontend
description: A Helm chart for deploying Customer Support Panel Frontend
type: application
version: 1.0.0
# renovate: image=customer-support-panel-frontend
appVersion: vi-prod-v0.0.44
kubeVersion: ">=1.22.0-0"
keywords:
  - customer-support
  - frontend
  - web
  - fintech
home: https://fintech-farm.com/
sources:
  - https://github.com/fintech-farm/customer-support-panel-frontend
maintainers:
  - name: Fintech Farm DevOps Team
    email: devops@fintech-farm.com
icon: https://fintech-farm.com/assets/logo.png
annotations:
  artifacthub.io/changes: |
    - "feat: Initial release of customer-support-panel-frontend"
    - "fix: Updated default resource limits for improved stability"
    - "docs: Added README with installation instructions"
    - "chore: Improved templating for better customization"
