apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 31.1.0
# renovate: image=traefik
appVersion: v3.1.4
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: 🐛 update CRD to v3.1"
    - "feat: ✨ input validation using schema"
    - "feat: ✨ add AllowACMEByPass and improve schema/doc on ports values"
    - "feat: add new webhooks and removes unnecessary ones"
    - "feat(deps): update traefik docker tag to v3.1.3"
    - "chore(release): 🚀 publish v31.1.0"
