apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 33.1.0
# renovate: image=traefik
appVersion: v3.2.1
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: :bug: support specifying plugins storage"
    - "fix(Traefik): support for entrypoint option on allowACMEByPass"
    - "fix(Traefik Proxy): allowEmptyServices not disabled when set to false"
    - "fix(Traefik Hub): compatibility with Traefik Proxy v3.2"
    - "fix(KubernetesCRD): 🐛 IngressClass should be readable even when kubernetesIngress is disabled"
    - "feat(deps): update traefik docker tag to v3.2.1"
    - "feat(Traefik Proxy): add `abortOnPluginFailure` field"
    - "feat(Traefik Hub): add APICatalogItem and ManagedSubscription support"
    - "docs: 📚️ fix typos in values and readme"
    - "chore(release): 🚀 publish v33.1.0-rc1"
