apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 20.7.0
appVersion: v2.9.6
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "⬆️  Update default Traefik release to v2.9.6"
    - "🐛 Don't fail when prometheus is disabled (#756)"
    - ":bug: Fix typo on bufferingSize for access logs (#753)"
    - "✨ support for Gateway annotations"
    - "add keywords [networking], for artifacthub category quering"
    - ":adhesive_bandage: Add quotes for artifacthub changelog parsing (#748)"
