apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
<<<<<<< HEAD
<<<<<<< HEAD
version: 9.9.0
=======
version: 9.8.3
>>>>>>> Bump chart version
=======
version: 9.8.4
>>>>>>> Increment chart version
appVersion: 2.3.1
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
