apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 30.1.0
# renovate: image=traefik
appVersion: v3.1.2
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: disable default HTTPS listener for gateway"
    - "fix(Gateway API): wildcard support in hostname"
    - "fix(Gateway API): use Standard channel by default"
    - "feat: ✨ rework namespaced RBAC with `disableClusterScopeResources`"
    - "chore(release): 🚀 publish v30.1.0"
    - "chore(deps): update traefik docker tag to v3.1.2"
    - "chore(deps): update traefik docker tag to v3.1.1"
