apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 34.0.0
# renovate: image=traefik
appVersion: v3.3.1
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix(Traefik Proxy)!: use namespaceOverride as expected"
    - "fix(Traefik Proxy)!: move redirectTo => redirections"
    - "fix(Gateway API): status should not use default service when it's disabled"
    - "feat(deps): update traefik docker tag to v3.3.1"
    - "feat(deps): update traefik docker tag to v3.2.3"
    - "feat(Traefik Proxy): apply migration guide to v3.3"
    - "feat(Traefik Proxy): add support for experimental FastProxy"
    - "feat(Traefik Hub): add support for AI Gateway"
    - "feat(Chart): :package: add optional separated chart for CRDs"
    - "feat(CRDs): update CRDs for Traefik Proxy v3.3.x"
    - "chore(release): publish v34.0.0"
    - "chore(Gateway API): :recycle: remove template from values"
