apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 28.0.0
# renovate: image=traefik
appVersion: v3.0.0
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "style: 🎨 consistent capitalization on `--entryPoints` CLI flag"
    - "fix: 🐛 only expose http3 port on service when TCP variant is exposed"
    - "fix: 🐛 logs filters on status codes"
    - "feat: ✨ add support of `experimental-v3.0` unstable version"
    - "feat: ability to override liveness and readiness probe paths"
    - "feat(ports): add transport options"
    - "chore(release): publish v28.0.0"
