---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - https://github.com/traefik/traefik-helm-chart/traefik/crds/
  - hub.traefik.io_accesscontrolpolicies.yaml
  - hub.traefik.io_apiaccesses.yaml
  - hub.traefik.io_apiportals.yaml
  - hub.traefik.io_apiratelimits.yaml
  - hub.traefik.io_apis.yaml
  - hub.traefik.io_apiversions.yaml
  - hub.traefik.io_edgeingresses.yaml
