{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer-support-panel-frontend.name" . }}
data:
  conf: {{ .Values.configmap.data.conf | quote }}
{{- end }}
