{{- if and (.Values.gateway).enabled (.Values.providers.kubernetesGateway).enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ default "traefik-gateway" .Values.gateway.name }}
  namespace: {{ template "traefik.namespace" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ default "traefik" .Values.gatewayClass.name }}
  listeners:
    {{ with .Values.ports.web }}
    - name: web
      port: {{ .port }}
      protocol: HTTP
      {{- with $.Values.gateway.namespacePolicy }}
      allowedRoutes:
        namespaces:
          from: {{ . }}
      {{- end }}
    {{- end }}
    {{ with .Values.ports.websecure }}
     {{- if $.Values.gateway.certificateRefs }}
    - name: websecure
      port: {{ $.Values.ports.websecure.port }}
      protocol: HTTPS
        {{- with $.Values.gateway.namespacePolicy }}
      allowedRoutes:
        namespaces:
          from: {{ . }}
        {{- end }}
      tls:
        certificateRefs:
          {{- toYaml $.Values.gateway.certificateRefs | nindent 10 }}
      {{- end }}
    {{- end }}
{{- end }}
