{{- if .Values.providers.kubernetesGateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: {{ template "traefik.namespace" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: {{ .Values.ports.web.port }}
      protocol: HTTP
      {{- with .Values.gateway.namespacePolicy }}
      allowedRoutes:
        namespaces:
          from: {{ . }}
      {{- end }}
    {{- if .Values.gateway.certificate }}
    - name: websecure
      port: {{ $.Values.ports.websecure.port }}
      protocol: HTTPS
      {{- with .Values.gateway.namespacePolicy }}
      allowedRoutes:
        namespaces:
          from: {{ . }}
      {{- end }}
      tls:
        certificateRefs:
          - name: {{ .Values.gateway.certificate.name }}
            group: {{ .Values.gateway.certificate.group }}
            kind: {{ .Values.gateway.certificate.kind }}
    {{- end }}
{{- end }}
