{{- if .Values.ingressClass.enabled -}}
  {{- if and (semverCompare ">=1.18-0" .Capabilities.KubeVersion.Version) (semverCompare ">=2.3" .Values.image.tag) -}}
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.ingressClass.isDefaultClass | quote }}
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ template "traefik.fullname" . }}
spec:
  controller: traefik.io/ingress-controller
  {{- end }}
{{- end }}
