{{- if .Values.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ include "customer-support-panel-frontend.name" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "customer-support-panel-frontend.name" . }}
                port:
                  number: {{ .Values.service.ports.0.port }}
{{- end }}
