{{- if .Values.metrics.prometheus.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "traefik.fullname" . }}
  {{- if .Values.metrics.prometheus.prometheusRule.namespace }}
  namespace: {{ .Values.metrics.prometheus.prometheusRule.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.metrics.prometheus.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.metrics.prometheus.prometheusRule.rules }}
  groups:
  - name: {{ template "traefik.name" . }}
    rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
