{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-support-panel-frontend.name" . }}
type: Opaque
data:
  my-secret-key: {{ .Values.secret.mySecret | b64enc | quote }}
{{- end }}
