{{- if (and .Values.metrics.prometheus.service.enabled (not .Values.hub.enabled)) -}}
apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: {{ template "traefik.namespace" . }}
  {{- template "traefik.metrics-service-metadata" . }}
  annotations:
  {{- with .Values.metrics.prometheus.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "traefik.metricslabelselector" . | nindent 4 }}
  ports:
  - port: {{ .Values.ports.metrics.port }}
    name: "metrics"
    targetPort: metrics
    protocol: TCP
    {{- if .Values.ports.metrics.nodePort }}
    nodePort: {{ .Values.ports.metrics.nodePort }}
    {{- end }}
{{- end -}}
