{{- if .Values.service.enabled -}}

{{ $tcpPorts := dict }}
{{ $udpPorts := dict }}
{{ $exposedPorts := false }}
{{- range $name, $config := .Values.ports }}
  {{- if or $config.http3 (eq (toString $config.protocol) "UDP") }}
    {{ $_ := set $udpPorts $name $config }}
  {{- end }}
  {{- if eq (toString (default "TCP" $config.protocol)) "TCP" }}
    {{ $_ := set $tcpPorts $name $config }}
  {{- end }}
  {{- if (eq $config.expose true) }}
    {{ $exposedPorts = true }}
  {{- end }}
{{- end }}

{{- if (eq $exposedPorts false) }}
  {{ fail "You need to expose at least one port or set enabled=false to service" }}
{{- end }}

{{- if  $tcpPorts }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
  annotations:
  {{- with (merge .Values.service.annotationsTCP .Values.service.annotations) }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- $type := default "LoadBalancer" .Values.service.type }}
  type: {{ $type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range $name, $config := $tcpPorts }}
  {{- if $config.expose }}
  - port: {{ default $config.port $config.exposedPort }}
    name: {{ $name }}
    targetPort: {{ $name | quote }}
    protocol: {{ default "TCP" $config.protocol | quote }}
    {{- if $config.nodePort }}
    nodePort: {{ $config.nodePort }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if eq $type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 6 }}
  {{- end -}}
  {{- end -}}
  {{- with .Values.service.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 6 }}
  {{- end -}}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}  
{{- end }}

{{- if  $udpPorts }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}-udp
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
  annotations:
  {{- with (merge .Values.service.annotationsUDP .Values.service.annotations) }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- $type := default "LoadBalancer" .Values.service.type }}
  type: {{ $type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range $name, $config := $udpPorts }}
  {{- if $config.expose }}
  - port: {{ default $config.port $config.exposedPort }}
    name: {{ $name }}
    targetPort: {{ $name | quote }}
    protocol: {{ default "UDP" $config.protocol | quote }}
    {{- if $config.nodePort }}
    nodePort: {{ $config.nodePort }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if eq $type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 6 }}
  {{- end -}}
  {{- end -}}
  {{- with .Values.service.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 6 }}
  {{- end -}}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
{{- end }}
{{- end -}}
