{{- range $name, $config := .Values.tlsOptions }}
apiVersion: traefik.io/v1
kind: TLSOption
metadata:
  name: {{ $name }}
  namespace: {{ template "traefik.namespace" $ }}
  labels:
    {{- include "traefik.labels" $ | nindent 4 }}
spec:
  {{- toYaml $config | nindent 2 }}
---
{{- end -}}
