{{- if .Values.traefik -}}
{{ include "traefik-crds.render-crds" (dict "scope" . "path" "crds-files/traefik/*.yaml") }}
{{- end }}

{{- if eq (.Values.hub | toString) "true" -}}
{{ include "traefik-crds.render-crds" (dict "scope" . "path" "crds-files/hub/*.yaml") }}
{{- end }}

{{- if eq (.Values.gateway_api | toString) "true" -}}
{{ include "traefik-crds.render-crds" (dict "scope" . "path" "crds-files/gateway_api/*.yaml") }}
{{- end }}
