apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
spec:
  group: traefik.containo.us
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              addPrefix:
                type: object
                properties:
                  prefix:
                    type: string
              stripPrefix:
                type: object
                properties:
                  prefixes:
                    type: array
                    items:
                      type: string
                  forceSlash:
                    type: boolean
              stripPrefixRegex:
                type: object
                properties:
                  regex:
                    type: array
                    items:
                      type: string
              replacePath:
                type: object
                properties:
                  path:
                    type: string
              replacePathRegex:
                type: object
                properties:
                  regex:
                    type: string
                  replacement:
                    type: string
              chain:
                type: object
                properties:
                  middlewares:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                        - name
                        - namespace
              ipWhiteList:
                type: object
                properties:
                  sourceRange:
                    type: array
                    items:
                      type: string
                  ipStrategy:
                    type: object
                    properties:
                      depth:
                        type: integer
                      excludedIPs:
                        type: array
                        items:
                          type: string
              headers:
                type: object
                properties:
                  customRequestHeaders:
                    type: object
                  customResponseHeaders:
                    type: object
                  accessControlAllowCredentials:
                    type: boolean
                  accessControlAllowHeaders:
                    type: array
                    items:
                      type: string
                  accessControlAllowMethods:
                    type: array
                    items:
                      type: string
                  accessControlAllowOrigin:
                    type: string
                  accessControlAllowOriginList:
                    type: array
                    items:
                      type: string
                  accessControlExposeHeaders:
                    type: array
                    items:
                      type: string
                  accessControlMaxAge:
                    type: integer
                  addVaryHeader:
                    type: boolean
                  allowedHosts:
                    type: array
                    items:
                      type: string
                  hostsProxyHeaders:
                    type: array
                    items:
                      type: string
                  sslRedirect:
                    type: boolean
                  sslTemporaryRedirect:
                    type: boolean
                  sslHost:
                    type: string
                  sslProxyHeaders:
                    type: object
                  sslForceHost:
                    type: boolean
                  stsSeconds:
                    type: integer
                  stsIncludeSubdomains:
                    type: boolean
                  stsPreload:
                    type: boolean
                  forceSTSheader:
                    type: boolean
                  frameDeny:
                    type: boolean
                  customFrameOptionsValue:
                    type: string
                  contentTypeNosniff:
                    type: boolean
                  browserXssFilter:
                    type: boolean
                  customBrowserXSSValue:
                    type: string
                  contentSecurityPolicy:
                    type: string
                  publicKey:
                    type: string
                  referrerPolicy:
                    type: string
                  featurePolicy:
                    type: string
                  isDevelopment:
                    type: boolean
              errors:
                type: object
                properties:
                  status:
                    type: array
                    items:
                      type: string
                  service:
                    type: object
                    properties:
                      sticky:
                        type: object
                        properties:
                          cookie:
                            type: object
                            properties:
                              name:
                                type: string
                              secure:
                                type: boolean
                              httpOnly:
                                type: boolean
                      namespace:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                      weight:
                        type: integer
                      responseForwarding:
                        type: object
                        properties:
                          flushInterval:
                            type: string
                      passHostHeader:
                        type: boolean
                      healthCheck:
                        type: object
                        properties:
                          path:
                            type: string
                          host:
                            type: string
                          scheme:
                            type: string
                          intervalSeconds:
                            type: integer
                          timeoutSeconds:
                            type: integer
                          headers:
                            type: object
                      strategy:
                        type: string
                      scheme:
                        type: string
                      port:
                        type: integer
                  query:
                    type: string
              rateLimit:
                type: object
                properties:
                  average:
                    type: integer
                  burst:
                    type: integer
                  sourceCriterion:
                    type: object
                    properties:
                      ipStrategy:
                        type: object
                        properties:
                          depth:
                            type: integer
                          excludedIPs:
                            type: array
                            items:
                              type: string
                      requestHeaderName:
                        type: string
                      requestHost:
                        type: boolean
              redirectRegex:
                type: object
                properties:
                  regex:
                    type: string
                  replacement:
                    type: string
                  permanent:
                    type: boolean
              redirectScheme:
                type: object
                properties:
                  scheme:
                    type: string
                  port:
                    type: string
                  permanent:
                    type: boolean
              basicAuth:
                type: object
                properties:
                  secret:
                    type: string
                  realm:
                    type: string
                  removeHeader:
                    type: boolean
                  headerField:
                    type: string
              digestAuth:
                type: object
                properties:
                  secret:
                    type: string
                  removeHeader:
                    type: boolean
                  realm:
                    type: string
                  headerField:
                    type: string
              forwardAuth:
                type: object
                properties:
                  address:
                    type: string
                  trustForwardHeader:
                    type: boolean
                  authResponseHeaders:
                    type: array
                    items:
                      type: string
                  tls:
                    type: object
                    properties:
                      caSecret:
                        type: string
                      caOptional:
                        type: boolean
                      certSecret:
                        type: string
                      insecureSkipVerify:
                        type: boolean
              inFlightReq:
                type: object
                properties:
                  amount:
                    type: integer
                  sourceCriterion:
                    type: object
                    properties:
                      ipStrategy:
                        type: object
                        properties:
                          depth:
                            type: integer
                          excludedIPs:
                            type: array
                            items:
                              type: string
                      requestHeaderName:
                        type: string
                      requestHost:
                        type: boolean
              buffering:
                type: object
                properties:
                  maxRequestBodyBytes:
                    type: integer
                  memRequestBodyBytes:
                    type: integer
                  maxResponseBodyBytes:
                    type: integer
                  memResponseBodyBytes:
                    type: integer
                  retryExpression:
                    type: string
              circuitBreaker:
                type: object
                properties:
                  expression:
                    type: string
              compress:
                type: object
                properties:
                  excludedContentTypes:
                    type: array
                    items:
                      type: string
              passTLSClientCert:
                type: object
                properties:
                  pem:
                    type: boolean
                  info:
                    type: object
                    properties:
                      notAfter:
                        type: boolean
                      notBefore:
                        type: boolean
                      sans:
                        type: boolean
                      subject:
                        type: object
                        properties:
                          country:
                            type: boolean
                          province:
                            type: boolean
                          locality:
                            type: boolean
                          organization:
                            type: boolean
                          commonName:
                            type: boolean
                          serialNumber:
                            type: boolean
                          domainComponent:
                            type: boolean
                      issuer:
                        type: object
                        properties:
                          country:
                            type: boolean
                          province:
                            type: boolean
                          locality:
                            type: boolean
                          organization:
                            type: boolean
                          commonName:
                            type: boolean
                          serialNumber:
                            type: boolean
                          domainComponent:
                            type: boolean
                      serialNumber:
                        type: boolean
              retry:
                type: object
                properties:
                  attempts:
                    type: integer
              contentType:
                type: object
                properties:
                  autoDetect:
                    type: boolean
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
