apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us
spec:
  group: traefik.containo.us
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              minVersion:
                type: string
              maxVersion:
                type: string
              cipherSuites:
                type: array
                items:
                  type: string
              curvePreferences:
                type: array
                items:
                  type: string
              clientAuth:
                type: object
                properties:
                  secretNames:
                    type: array
                    items:
                      type: string
                  clientAuthType:
                    type: string
                    enum:
                      - NoClientCert
                      - RequestClientCert
                      - VerifyClientCertIfGiven
                      - RequireAndVerifyClientCert
              sniStrict:
                type: boolean
              preferServerCipherSuites:
                type: boolean
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced
