name: Deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    if: github.repository == 'traefik/traefik-helm-chart'
    env:
      TMPDIR: /tmp

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: |
          curl -L https://git.io/get_helm.sh | bash -s -- -v v3.9.4
          curl -sSL -o /tmp/ct.tgz https://github.com/helm/chart-testing/releases/download/v3.7.1/chart-testing_3.7.1_linux_amd64.tar.gz
          tar xzf /tmp/ct.tgz -C /tmp && sudo cp /tmp/ct /usr/local/bin/ct && command -v ct
          pip install yamale

      - name: Make
        run: make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: repo/
          clean: false
