name: Publish Chart on GHCR OCI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy LICENSE and README.md for packaging
        run: |
          cp ./README.md ./traefik/README.md
          cp ./EXAMPLES.md ./traefik/EXAMPLES.md
          cp ./LICENSE ./traefik/LICENSE

      - name: Publish Helm chart to the ghcr.io registry
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: charts
          repository:  traefik
          tag: v29.0.0
          path: ./traefik
          registry: ghcr.io
          registry_username: traefiker
          registry_password: ${{ secrets.GHCR_TOKEN }}
