---
name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout master
        run: git checkout master && git checkout - && git rev-parse HEAD

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Test if it's a release PR
        id: check
        run: |
          if ! [ -z "$(git show traefik/Chart.yaml | grep version:)" ]; then
            echo "release=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check docs
        if: steps.check.outputs.release
        run: |
          make docs
          if ! [ -z "$(git status | grep traefik/VALUES.md)" ]; then
            echo "Traefik values have changed. Run make docs"
            exit 1
          fi

      - name: Create kind cluster
        if: steps.check.outputs.release
        uses: helm/kind-action@v1.8.0

      - name: Install LB on Kind
        if: steps.check.outputs.release
        run: |
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml
          kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s
          kubectl apply -f hack/metallb-config.yaml


      - name: Check install on Kind
        if: steps.check.outputs.release
        run: |
          make test-install
