{{- if and .Values.rbac.enabled (not .Values.rbac.namespaced) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
  {{- include "traefik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "traefik.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "traefik.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end -}}
