{{- if not .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customer-support-panel-frontend.serviceAccountName" . }}
  namespace: {{ include "customer-support-panel-frontend.namespace" . }}
  labels:
    {{- include "customer-support-panel-frontend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
